Feature/jan/actualizar mascotas
Janescobar92/PETBUDDY-FRONTEND pull request #11
Opened 2020-12-02 11:15 UTC by Janescobar92

@jc-alcaldev 
@JuanLGC 
@JimenaEB
![image](https://user-images.githubusercontent.com/70323466/100865740-09432200-3498-11eb-9ab1-b6fd28ea9ee3.png)

2020-12-02 14:40 UTC, Janescobar92 commented
![image](https://user-images.githubusercontent.com/70323466/100886884-a0b66e00-34b4-11eb-92b7-a56969fb3fd3.png)
además ya tiene el css pero no se como tratar las imágenes aún

2020-12-02 16:00 UTC, JimenaEB commented
PERO @Janescobar92!!!!
50 ficheros en una PR???? Te mato

2020-12-02 16:01 UTC, JimenaEB commented
> ![image](https://user-images.githubusercontent.com/70323466/100886884-a0b66e00-34b4-11eb-92b7-a56969fb3fd3.png)
> además ya tiene el css pero no se como tratar las imágenes aún

Baja la foto porque el nombre no se lee bien

2020-12-02 17:14 UTC, JimenaEB requested changes

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/Login_form.jsx
> +	);
Por fi, cuando puedas cambialo por un modal 🙏🏻 
No es prioritario

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/Login_form.jsx
> +					{" "}
No pillo por qué esto aquí

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/description_card.jsx
> +	}
no será mejor usar un .find() aquí? Creo que te puede servir

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/hcard.jsx
> +import "../../styles/h_card_style.scss";
No los separes con saltos de línea

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/hcard.jsx
> +	date: PropTypes.string,
No debería ser string

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_form.jsx
> +						<option value="jugueton">Jugueton</option>
Mejor si te las traes del back las opciones

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_form.jsx
> +					<label htmlFor="Affections">Afeciones</label>
Afecciones

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_form.jsx
> +						<option value={false}>No</option>
Mejor que por defecto sea False

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_update_form.jsx
> +	}
Mejor usar .find()

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_update_form.jsx
> +					actions.updateUserPet(actions.updatePetForm());
Por qué como parámetro si la puedes llamar desde la action?

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_update_form.jsx
> +						<option value="True" selected disabled>
El valos por defecto si no hay nada seleccionado deberia ser null mejor, no?

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/pets_update_form.jsx
> +						</option>
igual aquí

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/register_form.jsx
> +	);
Mejor que no sea un alert

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/register_form.jsx
> +				{" "}
Creo que aquí sobra

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/register_form.jsx
> +	);
Dónde compruebas que son iguales?

2020-12-02 17:14 UTC, JimenaEB commented on src/js/component/vpetscard.jsx
> +			{cards}
Si va actuar como componente mejor con mayúscula delante

2020-12-02 17:14 UTC, JimenaEB commented on src/js/layout.js
>  						</Route>
Esta la podéis quitar?

2020-12-02 17:14 UTC, JimenaEB commented on src/js/store/appContext.js
> +				state.actions.getLocalSorageToken();
Pero no tienes porqué tener el token porque tengas algo en el local storage no?

2020-12-02 17:14 UTC, JimenaEB commented on src/js/store/flux.js
> +			indexChoosed: null
Intenta ya ir sustituyendo por lo que traes del backend

2020-12-02 17:14 UTC, JimenaEB commented on src/styles/pets_form.scss
> +    width: 360px;
No uséis px

2020-12-02 17:14 UTC, JimenaEB commented on src/styles/containers_margins.scss
> +@media (max-width: 1024px) { }
pero si están vacías no las necesitas

2020-12-02 17:14 UTC, JimenaEB commented on src/js/views/profile.js
> +	}
.find()

2020-12-02 17:14 UTC, JimenaEB commented on src/js/views/home.js
> +};
Pero carga tu home y borra ya la de Rigo

2020-12-02 17:14 UTC, JimenaEB commented on src/js/views/history.js
> +			<h2>Has trabajado para</h2>
No debiera ser un h2 porque semánticamente no concuerda

2020-12-02 17:14 UTC, JimenaEB commented on src/js/store/flux.js
>  			},
Borra esta ya

2020-12-02 17:14 UTC, JimenaEB commented on src/js/store/flux.js
> +				}
Haz una ternaria

2020-12-03 21:34 UTC, Janescobar92 commented on src/js/component/Login_form.jsx
> +	);
corregido

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/component/Login_form.jsx
> +					{" "}
corregido

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/component/description_card.jsx
> +	}
corregido

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/component/hcard.jsx
> +import "../../styles/h_card_style.scss";
corregido

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/views/profile.js
> +	}
corregido

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/views/home.js
> +};
la tiene juan carlos

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/store/flux.js
>  			},
corregido

2020-12-03 21:35 UTC, Janescobar92 commented on src/js/store/flux.js
> +				}
corregido

2020-12-03 21:36 UTC, Janescobar92 commented
ya están aplicadas todas las correcciones

2020-12-04 14:27 UTC, JuanLGC requested changes

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/comments-container.jsx
> +	//  aqui va un map
borra comentarios

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/description-container.jsx
> +	//  aqui va un map
pon el map, no el comentario

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/navbar.js
> +						<p>Hitorial</p>
Historial*

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/pets-cards-container.jsx
> +	// const handleClick = () => setShowResults(!showResults);
borra lo que necesites

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/pets_form.jsx
> +							Selecionar
Seleccionar

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/pets_form.jsx
> +							Selecionar
Seleccionar

2020-12-04 14:27 UTC, JuanLGC commented on src/js/component/shops-cards-container.jsx
> +	//  aqui va un map
...

2020-12-04 14:27 UTC, JuanLGC commented on src/js/store/flux.js
> +			route: " https://3000-c948bd0b-ac9d-4c50-a69e-4fc330593eb4.ws-eu03.gitpod.io"
esto debe desaparecer 📦

2020-12-04 14:27 UTC, JuanLGC commented on src/styles/jumbotron.scss
> +    // }
si no lo usas, borralo

2020-12-04 15:15 UTC, JimenaEB approved these changes

2020-12-04 15:17 UTC, merged