Feature/jan/ver contratos previos
Janescobar92/PETBUDDY-FRONTEND pull request #17
Opened 2020-12-06 14:18 UTC by Janescobar92

@jc-alcaldev 
@JuanLGC 
@JimenaEB

![image](https://user-images.githubusercontent.com/70323466/101282565-3ebc7800-37d6-11eb-953c-da24cd076352.png)

2020-12-09 11:00 UTC, JimenaEB requested changes

2020-12-09 11:00 UTC, JimenaEB commented on src/js/store/flux.js
> +				fetch("https://3000-c948bd0b-ac9d-4c50-a69e-4fc330593eb4.ws-eu03.gitpod.io/user/workedfor/1", {
Pon la de heroku

2020-12-09 11:00 UTC, JimenaEB commented on src/styles/h_card_style.scss
> +    border-radius: 10px;
px ¬¬

2020-12-09 11:00 UTC, JimenaEB commented on src/js/store/appContext.js
> +			// state.actions.getWhoHireYouHistory();
No llamas a ninguna action en el useEffect?

2020-12-09 11:22 UTC, Janescobar92 commented on src/js/store/flux.js
> +				fetch("https://3000-c948bd0b-ac9d-4c50-a69e-4fc330593eb4.ws-eu03.gitpod.io/user/workedfor/1", {
no puedo en heroku no existe

2020-12-09 11:22 UTC, Janescobar92 commented on src/styles/h_card_style.scss
> +    border-radius: 10px;
ok lo cambio

2020-12-09 11:23 UTC, Janescobar92 commented on src/js/store/appContext.js
> +			// state.actions.getWhoHireYouHistory();
no entiendo

2020-12-10 10:52 UTC, JuanLGC approved these changes

2020-12-10 10:52 UTC, JuanLGC commented on src/js/store/appContext.js
> +			// state.actions.getWhoHireYouHistory();
Borrar los comments

2020-12-10 10:52 UTC, JuanLGC commented on src/js/store/appContext.js
>  			 * This function is the equivalent to "window.onLoad", it only runs once on the entire application lifetime
puedes borrar todo lo que nno necesites del boilerplate

2020-12-10 10:52 UTC, JuanLGC commented on src/styles/h_card_style.scss
> +    border-radius: 10px;
🥩

2020-12-10 19:53 UTC, merged